### ISSUE TITLE
Current position is before the first row

### ISSUE THREAD

**Issue by fablue** [speedment/speedment#386] opened 2017-03-21 13:39 UTC
Hey!  I recently tried to upgrade from 3.0.2 to 3.0.5 and without changing some other code i get this Exception thrown:
java.sql.SQLDataException: Current position is before the first row

This is the line producing the Exception 

```java 
return users().stream().filter(User.TOKEN.equal(token)).findAny().orElse(null);
```

Weirdly enough: The server works fine but prints this exception all the time!
Am i doing something wrong here?

Thanks in advance :)

**Comment by fablue** [comment] 2017-03-21 13:41
Ah full stacktrace here! 
```java
2017-03-21 14:39:58.687 ERROR 6386 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.speedment.runtime.core.exception.SpeedmentException: java.sql.SQLDataException: Current position is before the first row] with root cause

org.mariadb.jdbc.internal.util.dao.QueryException: Current position is before the first row
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.throwError(MariaSelectResultSet.java:553) ~[mariadb-java-client-1.4.0.jar:na]
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.checkObjectRange(MariaSelectResultSet.java:536) ~[mariadb-java-client-1.4.0.jar:na]
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.getLong(MariaSelectResultSet.java:1008) ~[mariadb-java-client-1.4.0.jar:na]
	at org.fablue.lm.database.lime.lime.user.generated.GeneratedUserSqlAdapter.apply(GeneratedUserSqlAdapter.java:49) ~[classes/:na]
	at com.speedment.runtime.core.internal.stream.StreamUtil$ResultSetIterator.next(StreamUtil.java:111) ~[runtime-core-3.0.5.jar:na]
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469) ~[na:1.8.0_121]
	at com.speedment.runtime.core.internal.stream.builder.streamterminator.ReferenceStreamTerminator.findAny(ReferenceStreamTerminator.java:144) ~[runtime-core-3.0.5.jar:na]
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.lambda$findAny$16(ReferenceStreamBuilder.java:369) ~[runtime-core-3.0.5.jar:na]
	at com.speedment.runtime.core.internal.stream.builder.AbstractStreamBuilder.finallyCloseReference(AbstractStreamBuilder.java:184) ~[runtime-core-3.0.5.jar:na]
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.findAny(ReferenceStreamBuilder.java:369) ~[runtime-core-3.0.5.jar:na]
	at org.fablue.lm.controller.AbstractController.byToken(AbstractController.java:74) ~[classes/:na]
	at org.fablue.lm.controller.MessageMetaGetController.getMeta(MessageMetaGetController.java:26) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by Pyknic** [comment] 2017-03-21 16:07
Of what you describe it looks like you are doing everything okey. I will try the 3.0.5 version of the connector and see if I can reproduce this. Sounds like the internal class doesn't call `hasNext()` before applying `next()` on the `ResultSet`. Since the element exists, it works, but MariaDB might throw an exception to let us know that we should check the result before assuming anything.

**Comment by fablue** [comment] 2017-03-21 16:11
Let me know if you need anything from me :smiley:

**Comment by Pyknic** [comment] 2017-05-10 18:46
This should be fixed now! I rewrote the `ResultSetIterator` since there was several issues with it. Please let me know if you find any additional problems and sorry for the delay.

**Comment by fablue** [comment] 2017-05-10 18:50
Thank you very much! I will test as soon as possible!  :+1: 
Love your project :heart:

**Comment by fablue** [comment] 2017-06-03 20:19
Sorry for testing it so late, but still open in 3.0.10 =(

```
 :: Speedment by Speedment, Inc.:: (v3.0.10) 

2017-06-03T20:16:23.004Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - Speedment (Open Source) version 3.0.10 by Speedment, Inc. Specification version 3.0
2017-06-03T20:16:23.004Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - Java Platform API Specification 1.8 by Oracle Corporation. Implementation Oracle Corporation 1.8.0_131 by Oracle Corporation
2017-06-03 22:16:23.009  WARN 6816 --- [       Thread-3] java.util.prefs                          : Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2017-06-03T20:16:23.140Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - MySQL, 10.2.6-MariaDB, MariaDB connector/J 1.4.0, JDBC version 4.0
2017-06-03T20:16:23.207Z DEBUG [http-nio-8080-exec-1] (#STREAM) - SELECT `id`,`token`,`firebase`,`initial`,`timestamp_location`,`distance`,`longitude`,`latitude` FROM `lime`.`user` WHERE (`lime`.`user`.`token`  = ? COLLATE utf8_bin), values:...]
..]
2017-06-03T20:16:23.278Z DEBUG [http-nio-8080-exec-1] (#STREAM) - SELECT `id`,`parent_id`,`user_id`,`channel`,`timestamp`,`color`,`longitude`,`latitude`,`city`,`type`,`message`,`media_id` FROM `lime`.`message` WHERE (`lime`.`message`.`parent_id` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)), values:[9506, 9512, 9527, 9532, 9563, 9629, 9630, 9758, 9763, 9773, 9853, 9885, 9899, 9900, 9956, 10067, 10069, 10159, 10161, 10162, 10176, 10202, 10207, 10245, 10266, 10317, 10434, 10499, 10564, 10655, 10658, 10732, 10739, 10792, 10798, 10799, 10801, 10888, 10891, 10900, 10917, 10919, 10921, 10936, 10965, 11005, 11006, 11050, 11065, 11089, 11108, 11176, 11177, 11178, 11188, 11191, 11192, 11253, 11281, 11350, 11354, 11386, 11482, 11483, 11620, 11626, 11628, 11630, 11807, 11822, 11823, 11825, 11839, 11856, 11857, 11859, 11875, 11896, 11908, 11919, 11920, 11922, 11925, 11926, 11927, 11979, 12015, 12054, 12079, 12081, 12087, 12093, 12130, 12140, 12155, 12156, 12157, 12158, 12161, 12162]
[GET /message]: Request took: 766ms
2017-06-03T20:16:25.739Z DEBUG [http-nio-8080-exec-2] (#STREAM) - SELECT `id`,`token`,`firebase`,`initial`,`timestamp_location`,`distance`,`longitude`,`latitude` FROM `lime`.`user` WHERE (`lime`.`user`.`token`  = ? COLLATE utf8_bin), values:...]
2017-06-03T20:16:25.750Z DEBUG [http-nio-8080-exec-2] (#STREAM) - SELECT `id`,`parent_id`,`user_id`,`channel`,`timestamp`,`color`,`longitude`,`latitude`,`city`,`type`,`message`,`media_id` FROM `lime`.`message` WHERE (`lime`.`message`.`id` = ?), values:[12162]
2017-06-03T20:16:25.753Z DEBUG [http-nio-8080-exec-2] (#STREAM) - SELECT `id`,`url`,`data`,`aspect_ratio` FROM `lime`.`media` WHERE (`lime`.`media`.`id` = ?), values:[2342]
2017-06-03T20:16:25.756Z DEBUG [http-nio-8080-exec-2] (#STREAM) - SELECT `id`,`user_id`,`pseudo`,`realname`,`image` FROM `lime`.`channel` WHERE (`lime`.`channel`.`pseudo`  = ? COLLATE utf8_bin), values:[jho]
2017-06-03T20:16:25.759Z DEBUG [http-nio-8080-exec-2] (#STREAM) - SELECT `id`,`parent_id`,`user_id`,`channel`,`timestamp`,`color`,`longitude`,`latitude`,`city`,`type`,`message`,`media_id` FROM `lime`.`message` WHERE (`lime`.`message`.`parent_id` IN (?)), values:[12162]
2017-06-03T20:16:25.765Z ERROR [http-nio-8080-exec-2] (c.s.r.c.i.s.b.AbstractStreamBuilder) - java.sql.SQLDataException: Current position is before the first row
com.speedment.runtime.core.exception.SpeedmentException: java.sql.SQLDataException: Current position is before the first row
	at org.fablue.lm.database.lime.lime.message.generated.GeneratedMessageSqlAdapter.apply(GeneratedMessageSqlAdapter.java:63)
	at com.speedment.runtime.core.internal.stream.StreamUtil$ResultSetIterator.forEachRemaining(StreamUtil.java:196)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.speedment.runtime.core.internal.component.sql.override.def.reference.DefaultCollectTerminator.apply(DefaultCollectTerminator.java:49)
	at com.speedment.runtime.core.internal.manager.sql.SqlStreamTerminator.collect(SqlStreamTerminator.java:141)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.lambda$collect$8(ReferenceStreamBuilder.java:289)
	at com.speedment.runtime.core.internal.stream.builder.AbstractStreamBuilder.finallyCloseReference(AbstractStreamBuilder.java:189)
	at com.speedment.runtime.core.internal.stream.builder.ReferenceStreamBuilder.collect(ReferenceStreamBuilder.java:289)
	at org.fablue.lm.assembler.ModelPublicPostAssembler.getChats(ModelPublicPostAssembler.java:82)
	at org.fablue.lm.assembler.ModelPublicPostAssembler.assemble(ModelPublicPostAssembler.java:48)
	at org.fablue.lm.assembler.ModelPublicPostAssembler.assemble(ModelPublicPostAssembler.java:29)
	at org.fablue.lm.controller.MessageGetController.getMessage(MessageGetController.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLDataException: Current position is before the first row
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:115)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.throwError(MariaSelectResultSet.java:553)
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.checkObjectRange(MariaSelectResultSet.java:536)
	at org.mariadb.jdbc.internal.queryresults.resultset.MariaSelectResultSet.getLong(MariaSelectResultSet.java:1008)
	at org.fablue.lm.database.lime.lime.message.generated.GeneratedMessageSqlAdapter.apply(GeneratedMessageSqlAdapter.java:50)
	... 70 more
```

**Comment by Pyknic** [comment] 2017-06-03 23:03
Okey, I reopen this issue now.

**Comment by minborg** [comment] 2017-06-05 17:13
Would it be possible for you to post the application code that generates this error and also the SQL definition of that particular table? That way, we will be able to reproduce the issue.  Presumably you are doing something like this:
```
Message message = messages.stream()
    .filter(Message.PARENT_ID.in(12162))
    .findAny()
    .orElse(null);
```

**Comment by minborg** [comment] 2017-06-08 03:04
I am unable to reproduce this issue using MariaDB and either MariaDB JDBC driver 1.5.9 or 2.0.1 

Apparently there has been some issues with the MariaDB JDBC driver in the past (e.g. https://stackoverflow.com/questions/27037510/current-position-is-after-the-last-row-when-resultsetgetrow-returns-1) 

Which MariaDB JDBC version are you using? Can you share your code too?

**Comment by fablue** [comment] 2017-06-08 16:30
I was using version 1.4.0 and the issues seems to be fixed simply by upgrading to 1.5.9!
Thanks a lot ☺️

**Closed** 2017-06-08 16:48 UTC
Labels: bug

**Comment by fablue** [comment] 2017-06-08 18:16
Oh no... 
Everything looked just great on my windows test-server, but running the same code and the same application on my linux app-server results in the following:

```
2017-06-08T18:10:42.336Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - Speedment (Open Source) version 3.0.10 by Speedment, Inc. Specification version 3.0
2017-06-08T18:10:42.336Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - Java Platform API Specification 1.8 by Oracle Corporation. Implementation N/A 1.8.0_131 by N/A
2017-06-08T18:10:42.655Z INFO  [http-nio-8080-exec-1] (#APPLICATION_BUILDER) - MySQL, 10.0.29-MariaDB-0ubuntu0.16.10.1, MariaDB connector/J 2.0.2, JDBC version 4.2
2017-06-08T18:10:42.852Z ERROR [http-nio-8080-exec-3] (c.s.r.c.i.d.AsynchronousQueryResultImpl) - Error executing SELECT `id`,`token`,`firebase`,`initial`,`timestamp_location`,`distance`,`longitude`,`latitude` FROM `lime`.`user` WHERE (`lime`.`user`.`token`  = ? COLLATE utf8_bin), values=[H9zgAOdRoA3AumySDuljfIcuAeliU3RjC3OdeF_YQ1CFSfx3zt02qvxxQeXQsUPViJ_dcLrcCkUHj0YgH1uoaQ]
java.sql.SQLSyntaxErrorException: (conn:18774) COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'


``` 

I am using utf8mb4_general_ci as standard collation for my database and for my tables but utf8mb4_bin	for the column "token". 

Should speedment generate code like 

``` 
COLLATE utf8mb4_bin 
``` 

But even changing the column to utf8_bin does throw the exact same error =(

**Comment by minborg** [comment] 2017-06-08 19:40
@fablue Note that there is an even newer driver 2.0.1 out now.

**Comment by fablue** [comment] 2017-06-08 19:46
@minborg I tried that one too! The results above used 2.0.2

**Comment by minborg** [comment] 2017-06-08 19:48
@fablue ok. Thank you for your help with solving this issue!
