### ISSUE TITLE
PosgreSQL: Streaming resultset does not work

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#568] opened 2017-11-17 06:20 UTC
Cursor based ResultSet does not seem to work despite #565 being fixed

**Comment by lawesson** [comment] 2017-12-06 19:00
I cannot reproduce this problem. I have created a database with half a million film records, running this:
 
´´´java
try {
            films.stream().forEach(f -> {
                System.out.println(f);
                throw new RuntimeException("done!");
            });
            throw new IllegalStateException("was supposed to die before coming here!");
        } catch (RuntimeException r) {
            // quite what we expect.
        } 
```

finishes in 20ms when speedment is built with 

```
statement.setFetchSize(FETCH_SIZE)
```

and it takes 2000ms without that setting. This seems to indicate that the cursor based result set does indeed work.

**Comment by lawesson** [comment] 2018-05-09 17:07
Closing - unable to reproduce

**Closed by lawesson** 2018-05-09 17:07 UTC
Labels: bug, community request, wontfix
