### ISSUE TITLE
Databases that are plugged in are lost in GUI

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#114] opened 2016-01-26 01:06 UTC
If a new database type is plugged in, it will show up in the GUI if there are no previous speedment.json file present. However, if the file is present, the new database type is not shown in the GUI.

**Comment by Pyknic** [comment] 2016-01-26 01:44
This will probably be fixed when we get merging of two config-trees fixed.

**Comment by Pyknic** [comment] 2016-03-01 21:22
I havn't been able to reproduce this in the current develop branch. Merging should be fixed so if that was the cause it should already be fixed. I close this issue for now.

**Closed by Pyknic** 2016-03-01 21:22 UTC
Labels: bug, verify
