### ISSUE TITLE
Check size calculations for class in GUI

### ISSUE THREAD

**Issue by minborg** [speedment/speedment#76] opened 2015-12-04 18:18 UTC
Dec 04, 2015 10:15:10 AM com.sun.javafx.scene.control.skin.VirtualFlow addTrailingCells
INFO: index exceeds maxCellCount. Check size calculations for class com.speedment.internal.newgui.ProjectTreeController$1

**Comment by Pyknic** [comment] 2016-01-19 19:24
I can't reproduce this message. Has anyone else encountered this?

**Comment by Pyknic** [comment] 2016-01-28 17:18
I am closing this issue since we haven't encountered this again.

**Closed by Pyknic** 2016-01-28 17:18 UTC
Labels: question
