### ISSUE TITLE
Tool: settings.xml-overrides gets saved into speedment.json

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#679] opened 2018-06-19 08:06 UTC
If you open the tool, enter a different username and then save the file, it will be persisted into the `speedment.json` file. However, if you then rerun the tool, the default username is back. Same thing if you manually create a `speedment.json`-file and then run `mvn speedment:reload`, it is the default username that will be used.

**Comment by Pyknic** [comment] 2018-06-19 08:37
Hm, the reason for this seems to be that overrides done in `settings.xml` make it into not just the runtime version of the configuration model, but also the tool input fields. This means that if you save the same file you loaded, you will save the `settings.xml`-username into the `speedment.json`-file.

**Comment by lawesson** [comment] 2018-12-10 15:48
The overriding values mentioned in this issue probably refers to `settings.properties`.

**Comment by lawesson** [comment] 2018-12-11 19:05
I have tried to follow the description of this bug without being able to reproduce.

`settings.xml` (pressumably in `~/.m2`) does not affect the tool. Since #535 is fixed, I do not see how `settings.properties` does either. 

Closing issue, please reopen with description of how to reproduce if the problem persists.

**Closed by lawesson** 2018-12-11 19:05 UTC
Labels: bug, wontfix, z-tool
