### ISSUE TITLE
Wrong style of un-disabled fields

### ISSUE THREAD

**Issue by Pyknic** [speedment/speedment#617] opened 2018-04-23 16:56 UTC
It looks like the style doesn't update properly when Auto-fields are enabled in the tool. Look at the field `Package Location` in this example, it looks like it is disabled even though it is not, but it is still editable. This might be an issue in Java 10.

![screenshot at 2018-04-23 18-54-42](https://user-images.githubusercontent.com/5597672/39141415-0f16b8be-4728-11e8-837b-7a847cc7a791.png)

**Comment by Pyknic** [comment] 2018-04-23 17:00
Relaunching the tool fixed the problem. It might be related to the previous exceptions maybe.

**Comment by minborg** [comment] 2018-12-10 09:55
Unable to reproduce the issue under Java 11. I will close this issue.

<img width="1454" alt="screen shot 2018-12-10 at 10 54 26 am" src="https://user-images.githubusercontent.com/7457876/49724630-0c6cf400-fc6a-11e8-94ad-0e4b2cf8d39e.png">

**Closed by minborg** 2018-12-10 09:55 UTC
Labels: bug, z-tool
